### ISSUE TITLE
I tried to build this, but Firefox webdriver seems to block that

### ISSUE THREAD

**Issue by stoeps13** [lordofthejars/continuous-documentation#1]
Hi, I watched your video (Thank you very much for that talk and that repo) and think about to add the screenshot functionality to my documents.
I tried just to run gradle in that repository and it opens Firefox, but it keeps white and no screenshots are made.
I checked in the asciidoctorj-screenshot repo, but it seems not to be maintained any more. So downgrading Firefox seems sufficient, but it would be cooler to just use Chrome or an other webdriver instead of Firefox.
Any tips on that topic?

**Comment by lordofthejars** [comment]
You are right that it is not maintained. The error you are facing probably is because the version of geb that it is used in the extension. I would suggest you to first try to update geb version in the project and try it by yourself. If it works then send a PR to the project, and I will take care to talk with a guy to accept and release it :)

**Comment by stoeps13** [comment]
Thanks, already working on it. Can you give me a hint, how I use a local build asciidoctorj-screenshot with a project like continous-documentation repo?

build.gradle contains
```
   classpath 'org.asciidoctor:asciidoctorj-screenshot:0.1.1'
```
as a dependency, how can I use a local file instead? Sorry to bother you, but I'm not a dev and try to understand all that stuff.
